// <auto-generated />
using FirstAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstAPI.Migrations
{
    [DbContext(typeof(FirstAPIContext))]
    partial class FirstAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FirstAPI.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Nintendo",
                            Name = "The Legend of Zelda: Breath of the Wild",
                            ReleaseYear = 2017
                        },
                        new
                        {
                            Id = 2,
                            Company = "Santa Monica Studio",
                            Name = "God of War",
                            ReleaseYear = 2018
                        },
                        new
                        {
                            Id = 3,
                            Company = "Rockstar Games",
                            Name = "Red Dead Redemption 2",
                            ReleaseYear = 2018
                        },
                        new
                        {
                            Id = 4,
                            Company = "FromSoftware",
                            Name = "Elden Ring",
                            ReleaseYear = 2022
                        },
                        new
                        {
                            Id = 5,
                            Company = "CD Projekt",
                            Name = "Cyberpunk 2077",
                            ReleaseYear = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
